# See https://pre-commit.com, and https://pre-commit.ci for more information

ci:
  skip: [ cleanup, readme-gen ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: name-tests-test
      - id: pretty-format-json
        args:
          - --autofix
          - --indent
          - "	"
          - --top-keys
          - $schema,version,label,type,command,group,detail
      - id: requirements-txt-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      # Lints and auto-fix Python files using ruff
      - id: ruff-check
        args: [ --fix ]
        # Formats Python files using ruff
      - id: ruff-format

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      # Formats Markdown files using mdformat with ruff integration
      - id: mdformat
        additional_dependencies:
          - mdformat-ruff
          - ruff
        # Markdown files except README.md
        files: ^(?!README\.md).*\.md$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools>=75.0.0
        args: [--config-file=mypy.ini]

  #  - repo: https://github.com/DavidAnson/markdownlint-cli2
  #    rev: v0.18.1
  #    hooks:
  #    - id: markdownlint-cli2
  #      args: [--fix]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.22
    hooks:
      # Updates uv.lock, even if the pyproject.toml file was changed
      - id: uv-lock
        # Keeps the requirements.txt file in sync with uv.lock
      - id: uv-export

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-issue-config
      - id: check-github-issue-forms
      - id: check-github-workflows
      - id: check-jsonschema
        name: "Check pyproject.toml"
        types_or: [ toml ]
        files: (^|/)pyproject\.toml$
        args: [ --schemafile, "https://raw.github.com/SchemaStore/schemastore/master/src/schemas/json/pyproject.json" ]
      - id: check-jsonschema
        name: "Check tasks.json"
        types_or: [ json ]
        files: (^|/)tasks\.json$
        args: [ --schemafile, "https://raw.github.com/SchemaStore/schemastore/master/src/schemas/json/task.json" ]

  - repo: local
    hooks:
      - id: readme-gen
        name: Generating README.md using typer
        language: system
        entry: sh -c 'uv run typer voltamanager utils docs --name voltamanager --title "Volta Manager" --output README.md &>/dev/null && git add README.md'
        pass_filenames: false
      - id: cleanup
        name: Deletes cache directories
        language: system
        entry: >
          sh -c 'find . \( \
            -name __pycache__ -o \
            -name .pytest_cache -o \
            -name .mypy_cache -o \
            -name .ruff_cache -o \
            \) -type d -prune -print0 | xargs -0 rm -rf'
